pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  sensors:
    type: AnalyzerGroup
    path: Sensors
    analyzers:
      sick_ldmrs800001s01:
        type: GenericAnalyzer
        path: SICK LD-MRS
        timeout: 5.0
        find_and_remove_prefix: sick_ldmrs800001s01
        num_items: 1
